name: beats
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.4.0
  google_fonts: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  miniplayer: ^1.0.1
  
  audio_service: ^0.18.6
  just_audio: ^0.9.26

  http: ^0.13.4
  
  cached_network_image: ^3.2.1
  youtube_explode_dart: ^1.11.0

  flutter_bloc:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
